language: php

sudo: false

services:
    - mysql

php:
    - 7.1

env:
    - WP_VERSION=nightly WP_MULTISITE=0 NODE_RELEASE=stable
    - WP_VERSION=latest WP_MULTISITE=0 NODE_RELEASE=stable
    - WP_VERSION=latest WP_MULTISITE=1 NODE_RELEASE=stable

matrix:
    allow_failures:
    - env: WP_VERSION=nightly WP_MULTISITE=0 NODE_RELEASE=stable
    - php: 7.3
      env: WP_VERSION=latest WP_MULTISITE=0 NODE_RELEASE=stable

    include:
    - php: 7.2
      env: WP_VERSION=latest WP_MULTISITE=0 NODE_RELEASE=stable
    - php: 7.0
      env: WP_VERSION=latest WP_MULTISITE=0 NODE_RELEASE=stable
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=0 NODE_RELEASE=stable

## Cache composer and node bits
cache:
    apt: true
    directories:
        - vendor
        - node_modules
        - $HOME/.composer/cache

before_install:
    - | # Only do npm install if we're running the latest stable node (Pipe preserves subsequent whitespace)
      if [ $NODE_RELEASE == "stable" ]; then
          . $HOME/.nvm/nvm.sh;
          nvm install ${NODE_RELEASE};
          npm install;
      fi

before_script:
    - bash bin/init.sh
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    - ln -s . /tmp/wordpress/wp-content/plugins/pods

script:
    - vendor/bin/phpunit
    - | # Only run js tests if we're running the latest stable node (Pipe preserves subsequent whitespace)
      if [ $NODE_RELEASE == "stable" ]; then
          npm run test-dfv;
      fi
